# This is the network config written by 'subiquity'
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      dhcp4: false
      addresses:
        - 172.16.0.11/24  # Your desired static IP address and subnet mask
      nameservers:
        addresses:
          - 8.8.8.8      # Primary DNS server
          - 8.8.4.4      # Secondary DNS server (optional)

